Repository commonwarexyz/monorepo, pull requests merged in 2025-04, with the labels that each got.

#674 [deployer] remove unnecessary clone of `ip`
  deployer/src/ec2/update.rs
Labels: chore

#697 [release] 4-9-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#733 [utils] fix `quorum` calculation for unaligned `n`
  consensus/src/simplex/mod.rs
  consensus/src/threshold_simplex/mod.rs
  cryptography/src/bls12381/dkg/mod.rs
  utils/src/lib.rs
Labels: bug

#778 [runtime] Support `criterion::AsyncExecutor` + `rayon::ThreadPool`
  Cargo.lock
  Cargo.toml
  consensus/src/simplex/mocks/conflicter.rs
  consensus/src/simplex/mocks/outdated.rs
  consensus/src/threshold_simplex/actors/voter/actor.rs
  consensus/src/threshold_simplex/mocks/conflicter.rs
  consensus/src/threshold_simplex/mod.rs
  cryptography/Cargo.toml
  runtime/Cargo.toml
  runtime/src/benchmarks/context.rs
  runtime/src/benchmarks/mod.rs
  runtime/src/benchmarks/tokio.rs
  runtime/src/deterministic.rs
  runtime/src/lib.rs
  runtime/src/tokio/runtime.rs
  runtime/src/utils.rs
Labels: bug

#794 [release] 4-21-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#796 [cryptography] Always Implement and Drop `Zeroize`
  consensus/src/ordered_broadcast/mod.rs
  consensus/src/threshold_simplex/actors/voter/mod.rs
  consensus/src/threshold_simplex/mod.rs
  cryptography/Cargo.toml
  cryptography/src/bls12381/benches/dkg_recovery.rs
  cryptography/src/bls12381/benches/dkg_reshare_recovery.rs
  cryptography/src/bls12381/dkg/mod.rs
  cryptography/src/bls12381/primitives/group.rs
  cryptography/src/bls12381/primitives/poly.rs
  cryptography/src/bls12381/scheme.rs
  cryptography/src/ed25519/scheme.rs
  cryptography/src/secp256r1/scheme.rs
  examples/vrf/src/handlers/contributor.rs
Labels: security

#799 Remove leftover mentions of protoc/protobuf
  .github/actions/setup/action.yml
  p2p/src/authenticated/config.rs
  p2p/src/authenticated/mod.rs
  p2p/src/authenticated/network.rs
  p2p/src/authenticated/types.rs
Labels: documentation, code hygiene

#838 [release] 4-25-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#856 [release] v0.0.48
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release
