Repository commonwarexyz/monorepo, pull requests merged in 2025-06, with the labels that each got.

#1058 [release] v0.0.54
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#1092 [codec] Simple codec roundtrip fuzz harness
  .gitignore
  Cargo.lock
  Cargo.toml
  FUZZING.md
  codec/fuzz/Cargo.toml
  codec/fuzz/fuzz_targets/codec_roundtrip.rs
Labels: asymmetric research

#1155 [storage/index] Fix Middle Mutate Case
  storage/src/index/mod.rs
  storage/src/index/storage.rs
Labels: bug
