Repository commonwarexyz/monorepo, pull requests merged in 2025-01, with the labels that each got.

#319 [release] 1/6/25
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  examples/chat/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  runtime/Cargo.toml
  scripts/bump_versions.sh
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#376 [release] 1-20-25
  Cargo.lock
  Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#391 [CI] Add WASM Support for `consensus` and `storage`
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  consensus/Cargo.toml
  consensus/src/lib.rs
  consensus/src/simplex/mocks/relay.rs
  consensus/src/simplex/mod.rs
  consensus/src/simplex/prover.rs
  consensus/src/threshold_simplex/mocks/relay.rs
  consensus/src/threshold_simplex/mod.rs
  consensus/src/threshold_simplex/prover.rs
  storage/Cargo.toml
  storage/src/lib.rs
Labels: enhancement

#384 fix: prevent integer overflow in consensus proof verification
  consensus/src/simplex/prover.rs
  consensus/src/threshold_simplex/prover.rs
Labels: bug

#403 [storage/mmr] add serialization/deserialization for Proof structure
  storage/Cargo.toml
  storage/src/mmr/verification.rs
Labels: enhancement
