Repository commonwarexyz/monorepo, pull requests merged in 2025-03, with the labels that each got.

#556 [release] 3-6-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  docs/blogs/commonware-deployer.html
  docs/imgs/flood-grafana.png
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/flood/README.md
  examples/flood/src/bin/flood.rs
  examples/flood/src/lib.rs
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#564 [broadcast] Flatten `broadcast::linked`, rename `signer::Actor` to `Engine`
  Cargo.lock
  broadcast/src/linked/ack_manager.rs
  broadcast/src/linked/config.rs
  broadcast/src/linked/engine.rs
  broadcast/src/linked/ingress.rs
  broadcast/src/linked/metrics.rs
  broadcast/src/linked/mocks/application.rs
  broadcast/src/linked/mod.rs
  broadcast/src/linked/signer/mod.rs
  broadcast/src/linked/tip_manager.rs
Labels: code hygiene, chore

#574 [release] 3-8-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#580 [release] 3-9-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#601 [release] 3-13-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#605 [release] 3-14-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#619 [release] 3-16-25
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#631 Remove `SizedSerialize` in favor of `SizedCodec`
  Cargo.lock
  consensus/Cargo.toml
  consensus/src/ordered_broadcast/ack_manager.rs
  consensus/src/ordered_broadcast/prover.rs
  consensus/src/ordered_broadcast/serializer.rs
  consensus/src/ordered_broadcast/tip_manager.rs
  consensus/src/simplex/encoder.rs
  consensus/src/simplex/mocks/application.rs
  consensus/src/simplex/prover.rs
  consensus/src/threshold_simplex/encoder.rs
  consensus/src/threshold_simplex/mocks/application.rs
  consensus/src/threshold_simplex/prover.rs
  cryptography/src/bls12381/primitives/group.rs
  cryptography/src/bls12381/primitives/poly.rs
  cryptography/src/bls12381/scheme.rs
  cryptography/src/ed25519/scheme.rs
  cryptography/src/lib.rs
  cryptography/src/secp256r1/scheme.rs
  cryptography/src/sha256/mod.rs
  examples/bridge/Cargo.toml
  examples/bridge/src/application/actor.rs
  examples/vrf/Cargo.toml
  examples/vrf/src/handlers/utils.rs
  p2p/Cargo.toml
  p2p/src/authenticated/actors/tracker/address.rs
  p2p/src/simulated/network.rs
  resolver/src/p2p/mocks/key.rs
  storage/Cargo.toml
  storage/src/archive/storage.rs
  storage/src/bmt/mod.rs
  storage/src/journal/fixed.rs
  storage/src/metadata/storage.rs
  storage/src/mmr/bitmap.rs
  storage/src/mmr/verification.rs
  utils/src/array/fixed_bytes.rs
  utils/src/array/mod.rs
  utils/src/array/u64.rs
  utils/src/lib.rs
Labels: chore

#639 [p2p] Fix bug with tracker bitvec
  p2p/src/authenticated/actors/tracker/actor.rs
Labels: bug

#647 [consensus] Replace `Epocher` with `Monitor`
  consensus/src/lib.rs
  consensus/src/ordered_broadcast/ack_manager.rs
  consensus/src/ordered_broadcast/config.rs
  consensus/src/ordered_broadcast/engine.rs
  consensus/src/ordered_broadcast/ingress.rs
  consensus/src/ordered_broadcast/mocks/committer.rs
  consensus/src/ordered_broadcast/mocks/epocher.rs
  consensus/src/ordered_broadcast/mocks/mod.rs
  consensus/src/ordered_broadcast/mocks/monitor.rs
  consensus/src/ordered_broadcast/mod.rs
  consensus/src/simplex/mod.rs
  consensus/src/threshold_simplex/mod.rs
Labels: bug, code hygiene
