Repository commonwarexyz/monorepo, pull requests merged in 2025-05, with the labels that each got.

#884 [release] v0.0.49
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#895 [release] v0.0.50
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#935 [codec] Add conformity tests
  codec/src/types/bytes.rs
  codec/src/types/map.rs
  codec/src/types/net.rs
  codec/src/types/primitives.rs
  codec/src/types/tuple.rs
  codec/src/types/vec.rs
  codec/src/varint.rs
Labels: bug

#952 [runtime/utils] Add Write Buffer
  runtime/src/utils/buffer/mod.rs
  runtime/src/utils/buffer/read.rs
  runtime/src/utils/buffer/write.rs
  runtime/src/utils/mod.rs
  storage/src/journal/fixed.rs
  storage/src/journal/variable.rs
Labels: codex

#962 [runtime] Reduce Duplicate Metrics Usage (with `spawn_metrics!`)
  runtime/src/deterministic.rs
  runtime/src/lib.rs
  runtime/src/macros.rs
  runtime/src/tokio/runtime.rs
Labels: codex

#979 [cryptography/bls12381] Remove Bisection Recursion
  cryptography/src/bls12381/primitives/group.rs
  cryptography/src/bls12381/primitives/ops.rs
  cryptography/src/bls12381/primitives/variant.rs
Labels: codex

#980 [release] v0.0.51
  Cargo.lock
  Cargo.toml
  broadcast/Cargo.toml
  codec/Cargo.toml
  consensus/Cargo.toml
  cryptography/Cargo.toml
  deployer/Cargo.toml
  examples/bridge/Cargo.toml
  examples/chat/Cargo.toml
  examples/flood/Cargo.toml
  examples/log/Cargo.toml
  examples/vrf/Cargo.toml
  macros/Cargo.toml
  p2p/Cargo.toml
  resolver/Cargo.toml
  runtime/Cargo.toml
  storage/Cargo.toml
  stream/Cargo.toml
  utils/Cargo.toml
Labels: release

#993 [storage] Introduce `RMap`
  Cargo.lock
  storage/Cargo.toml
  storage/src/archive/storage.rs
  storage/src/index/benches/bench.rs
  storage/src/index/benches/insert.rs
  storage/src/lib.rs
  storage/src/rmap/benches/bench.rs
  storage/src/rmap/benches/insert.rs
  storage/src/rmap/mod.rs
Labels: jules
